apiVersion: v2
name: gatekeeper-library-constraints
description: Library of gateeper constraints
home: https://github.com/xenitab/gatekeeper-library
type: application
version: v0.6.1
appVersion: v0.6.1
