namePrefix: ""

constraints: []
  #- kind: K8sRequiredAnnotations
  #  name: foobar
  #  parameters:
  #    annotations:
  #      - key: "foo"
  #        allowedRegex: "bar"

mutationExcludedNamespaces: ["kube-system", "gatekeeper-system"]
assigns: []
  #- name: container-read-only-root-fs
