apiVersion: v2
name: gatekeeper-library-templates
description: Library of gateeper constraints
home: https://github.com/xenitab/gatekeeper-library
type: application
version: v0.7.3
appVersion: v0.7.3
